module.exports = {
  'array-callback-return': ['error', { allowImplicit: true }],
  'block-scoped-var': 'error',
  camelcase: 'off',
  'constructor-super': 'error',
  'default-case': ['error', { commentPattern: '^no default$' }],
  'dot-notation': ['error', { allowKeywords: true }],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'for-direction': 'error',
  'getter-return': ['error', { allowImplicit: true }],
  'guard-for-in': 'error',
  'lines-around-directive': [
    'error',
    {
      before: 'always',
      after: 'always',
    },
  ],
  'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
  'new-cap': [
    'error',
    {
      newIsCap: true,
      newIsCapExceptions: [],
      capIsNew: false,
      capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'],
    },
  ],
  'no-alert': 'off',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-buffer-constructor': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'off',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'except-parens'],
  'no-console': 'off',
  'no-const-assign': 'error',
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-continue': 'error',
  'no-control-regex': 'off',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-else-return': ['warn', { allowElseIf: false }],
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-function': [
    'error',
    {
      allow: ['arrowFunctions', 'functions', 'methods'],
    },
  ],
  'no-empty-pattern': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'warn',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'error',
  'no-implied-eval': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-misleading-character-class': 'error',
  'no-multi-assign': ['error'],
  'no-multi-str': 'error',
  'no-nested-ternary': 'off',
  'no-new': 'warn',
  'no-new-func': 'error',
  'no-new-object': 'error',
  'no-new-require': 'error',
  'no-new-symbol': 'error',
  'no-new-wrappers': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-path-concat': 'error',
  'no-plusplus': 'off',
  'no-proto': 'error',
  'no-prototype-builtins': 'off',
  'no-redeclare': 'error',
  'no-regex-spaces': 'off',
  'no-restricted-properties': [
    'error',
    {
      object: 'arguments',
      property: 'callee',
      message: 'arguments.callee is deprecated',
    },
    {
      object: 'global',
      property: 'isFinite',
      message: 'Use Number.isFinite instead. Beware, Number.isFinite behavior is not exactly the same',
    },
    {
      object: 'self',
      property: 'isFinite',
      message: 'Use Number.isFinite instead. Beware, Number.isFinite behavior is not exactly the same',
    },
    {
      object: 'window',
      property: 'isFinite',
      message: 'Use Number.isFinite instead. Beware, Number.isFinite behavior is not exactly the same',
    },
    {
      object: 'global',
      property: 'isNaN',
      message: 'Use Number.isNaN instead. Beware, Number.isNaN behavior is not exactly the same',
    },
    {
      object: 'self',
      property: 'isNaN',
      message: 'Use Number.isNaN instead. Beware, Number.isNaN behavior is not exactly the same',
    },
    {
      object: 'window',
      property: 'isNaN',
      message: 'Use Number.isNaN instead. Beware, Number.isNaN behavior is not exactly the same',
    },
    {
      property: '__defineGetter__',
      message: 'Use Object.defineProperty instead.',
    },
    {
      property: '__defineSetter__',
      message: 'Use Object.defineProperty instead.',
    },
    {
      object: 'Math',
      property: 'pow',
      message: 'Use the exponentiation operator (**) instead.',
    },
  ],
  'no-return-assign': ['error', 'always'],
  'no-script-url': 'error',
  'no-self-assign': [
    'error',
    {
      props: false,
    },
  ],
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'off',
  'no-template-curly-in-string': 'error',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-undef': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unused-expressions': ['error', { allowTaggedTemplates: true, allowShortCircuit: true }],
  'no-unused-labels': 'error',
  'no-unused-vars': ['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
  'no-use-before-define': ['error', { functions: true, classes: true, variables: true }],
  'no-useless-catch': 'off',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'off',
  'no-useless-rename': [
    'error',
    {
      ignoreDestructuring: false,
      ignoreImport: false,
      ignoreExport: false,
    },
  ],
  'no-var': 'error',
  'no-void': 'error',
  'no-with': 'error',
  'one-var': ['error', 'never'],
  'operator-assignment': ['error', 'always'],
  'prefer-const': [
    'error',
    {
      destructuring: 'any',
      ignoreReadBeforeAssign: true,
    },
  ],
  'prefer-numeric-literals': 'error',
  'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'off',
  radix: 'error',
  'require-yield': 'off',
  strict: ['error', 'never'],
  'symbol-description': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'vars-on-top': 'error',
  yoda: 'error',
  'import/export': 'error',
  'import/extensions': 'off',
  'import/first': 'error',
  'import/named': 'error',
  'import/newline-after-import': 'error',
  'import/no-absolute-path': 'error',
  'import/no-cycle': ['error', { maxDepth: Infinity }],
  'import/no-deprecated': 'error',
  'import/no-duplicates': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-named-default': 'error',
  'import/no-self-import': 'error',
  'import/no-unresolved': ['error', { commonjs: true, caseSensitive: true }],
  'import/no-useless-path-segments': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/order': ['error', { groups: [['builtin', 'external', 'internal']] }],
  'jest/consistent-test-it': 'off',
  'jest/expect-expect': 'warn',
  'jest/lowercase-name': 'off',
  'jest/no-alias-methods': 'off',
  'jest/no-commented-out-tests': 'error',
  'jest/no-disabled-tests': 'error',
  'jest/no-export': 'off',
  'jest/no-focused-tests': 'error',
  'jest/no-hooks': 'off',
  'jest/no-if': 'warn',
  'jest/no-jasmine-globals': 'error',
  'jest/no-jest-import': 'warn',
  'jest/no-large-snapshots': 'warn',
  'jest/no-mocks-import': 'off',
  'jest/no-standalone-expect': 'error',
  'jest/no-test-callback': 'off',
  'jest/no-test-prefixes': 'error',
  'jest/no-test-return-statement': 'off',
  'jest/no-truthy-falsy': 'off',
  'jest/prefer-called-with': 'off',
  'jest/prefer-expect-assertions': 'off',
  'jest/prefer-inline-snapshots': 'off',
  'jest/prefer-spy-on': 'off',
  'jest/prefer-strict-equal': 'warn',
  'jest/prefer-to-contain': 'error',
  'jest/prefer-to-have-length': 'error',
  'jest/prefer-todo': 'error',
  'jest/valid-expect-in-promise': 'error',
  'jest/valid-expect': 'error',
  'no-secrets/no-secrets': ['error', { tolerance: 6 }],
  'prettier/prettier': 'error',
  'arrow-body-style': 'off',
  'array-bracket-newline': 'off',
  'array-bracket-spacing': 'off',
  'array-element-newline': 'off',
  'arrow-parens': 'off',
  'arrow-spacing': 'off',
  'block-spacing': 'off',
  'brace-style': 'off',
  'comma-dangle': 'off',
  'comma-spacing': 'off',
  'comma-style': 'off',
  'computed-property-spacing': 'off',
  curly: 'off',
  'dot-location': 'off',
  'eol-last': 'off',
  'func-call-spacing': 'off',
  'function-call-argument-newline': 'off',
  'function-paren-newline': 'off',
  'generator-star': 'off',
  'generator-star-spacing': 'off',
  'implicit-arrow-linebreak': 'off',
  indent: 'off',
  'indent-legacy': 'off',
  'jsx-quotes': 'off',
  'key-spacing': 'off',
  'keyword-spacing': 'off',
  'linebreak-style': 'off',
  'lines-around-comment': 'off',
  'max-len': 'off',
  'multiline-ternary': 'off',
  'newline-per-chained-call': 'off',
  'new-parens': 'off',
  'no-arrow-condition': 'off',
  'no-comma-dangle': 'off',
  'no-confusing-arrow': 'off',
  'no-extra-parens': 'off',
  'no-extra-semi': 'off',
  'no-floating-decimal': 'off',
  'no-mixed-operators': 'off',
  'no-mixed-spaces-and-tabs': 'off',
  'no-multi-spaces': 'off',
  'no-multiple-empty-lines': 'off',
  'no-reserved-keys': 'off',
  'no-space-before-semi': 'off',
  'no-spaced-func': 'off',
  'no-tabs': 'off',
  'no-trailing-spaces': 'off',
  'no-whitespace-before-property': 'off',
  'no-wrap-func': 'off',
  'nonblock-statement-body-position': 'off',
  'object-curly-newline': 'off',
  'object-curly-spacing': 'off',
  'object-property-newline': 'off',
  'one-var-declaration-per-line': 'off',
  'operator-linebreak': 'off',
  'padded-blocks': 'off',
  'prefer-arrow-callback': 'off',
  'quote-props': 'off',
  quotes: 'off',
  'rest-spread-spacing': 'off',
  semi: 'off',
  'semi-spacing': 'off',
  'semi-style': 'off',
  'space-after-function-name': 'off',
  'space-after-keywords': 'off',
  'space-before-blocks': 'off',
  'space-before-function-paren': 'off',
  'space-before-function-parentheses': 'off',
  'space-before-keywords': 'off',
  'space-in-brackets': 'off',
  'space-in-parens': 'off',
  'space-infix-ops': 'off',
  'space-return-throw-case': 'off',
  'space-unary-ops': 'off',
  'space-unary-word-ops': 'off',
  'switch-colon-spacing': 'off',
  'template-curly-spacing': 'off',
  'template-tag-spacing': 'off',
  'unicode-bom': 'off',
  'wrap-iife': 'off',
  'wrap-regex': 'off',
  'yield-star-spacing': 'off',
  'testing-library/await-async-query': 'error',
  'testing-library/await-async-utils': 'error',
  'testing-library/no-await-sync-query': 'error',
  'testing-library/no-dom-import': 'off',
};
